# Generated by Django 2.1.2 on 2018-12-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181227_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readcount',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadCount',
        ),
    ]
